version: "3"
services:
  service:
    build: src/service/.
    environment:
      - ELASTICSEARCH_NODE=http://elasticsearch:9200
    expose:
      - 3000
  webclient:
    build: src/webclient/.
    expose:
      - 80
  elasticsearch:
    build: src/elasticsearch/.
    # image: "elasticsearch:7.5.2"
    # environment:
    #   - "discovery.type=single-node"
    expose:
      - 9200
      - 9300
  # https://www.domysee.com/blogposts/reverse-proxy-nginx-docker-compose
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 433:433
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
